"""Recursive delegated authority minting for META, X and Senju.

This module gives trusted internal agents the ability to create new authority profiles
for narrower tasks without turning profile creation into privilege escalation.

Core invariant:
    child_authority <= parent_authority

A child may itself mint another child while delegation depth remains, creating a real
recursive authority chain. Every generation is cryptographically identified by its
serialized content and records its parent and issuer.
"""
from __future__ import annotations

import dataclasses
import datetime as dt
import hashlib
import ipaddress
import json
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping

from .external import BUILTIN_AUTHORITY_SCOPES, ExternalAuthorityScope
from .private_network import PrivateNetworkPolicy

REGISTRY_SCHEMA = "senju-delegated-authority-registry/v1"
PROFILE_SCHEMA = "senju-delegated-authority/v1"
TRUSTED_ISSUERS = frozenset({"META", "X", "Senju"})
READ_ONLY_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})
CREDENTIAL_RANK = {"none": 0, "public_token": 1, "service_bearer": 2}


class AuthorityMintError(RuntimeError):
    """Raised when a requested child authority would exceed its parent."""


def _norm_host(value: str) -> str:
    host = str(value).strip().lower().rstrip(".")
    if not host or any(ch in host for ch in "/?#@"):
        raise AuthorityMintError(f"invalid authority host: {value!r}")
    try:
        return host.encode("idna").decode("ascii")
    except UnicodeError as exc:
        raise AuthorityMintError(f"invalid authority host: {value!r}") from exc


def _norm_methods(values: Iterable[str]) -> frozenset[str]:
    methods = frozenset(str(x).strip().upper() for x in values if str(x).strip())
    if not methods:
        raise AuthorityMintError("authority must retain at least one HTTP method")
    valid = {"GET", "HEAD", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"}
    bad = methods - valid
    if bad:
        raise AuthorityMintError(f"unsupported methods: {sorted(bad)}")
    return methods


def _network(value: str) -> ipaddress._BaseNetwork:
    try:
        return ipaddress.ip_network(value, strict=False)
    except ValueError as exc:
        raise AuthorityMintError(f"invalid CIDR: {value}") from exc


def _cidr_is_within(child: str, parent_cidrs: Iterable[str]) -> bool:
    c = _network(child)
    return any(c.version == p.version and c.subnet_of(p) for p in map(_network, parent_cidrs))


@dataclass(frozen=True)
class AuthorityProfile:
    profile_id: str
    issuer: str
    purpose: str
    parent_id: str | None
    generation: int
    created_at_utc: str
    can_delegate: bool
    delegation_depth_remaining: int

    allow_hosts: frozenset[str] = field(default_factory=frozenset)
    allowed_methods: frozenset[str] = field(default_factory=lambda: READ_ONLY_METHODS)
    allow_http: bool = False
    follow_redirects: bool = False
    allow_delete: bool = False
    rate_limit_per_minute: int = 12
    timeout_seconds: float = 8.0
    max_request_bytes: int = 0
    max_response_bytes: int = 512 * 1024
    retries: int = 1
    credential_scope: str = "none"

    allow_private_network: bool = False
    private_hosts: frozenset[str] = field(default_factory=frozenset)
    private_cidrs: tuple[str, ...] = ()

    fingerprint: str = ""
    schema: str = PROFILE_SCHEMA

    def to_dict(self) -> dict[str, Any]:
        data = dataclasses.asdict(self)
        data["allow_hosts"] = sorted(self.allow_hosts)
        data["allowed_methods"] = sorted(self.allowed_methods)
        data["private_hosts"] = sorted(self.private_hosts)
        return data

    def to_external_scope(self) -> ExternalAuthorityScope:
        if not self.allow_hosts:
            raise AuthorityMintError("profile has no public external-contact hosts")
        return ExternalAuthorityScope(
            scope_id=self.profile_id,
            target_service=self.purpose,
            allow_hosts=self.allow_hosts,
            allowed_methods=self.allowed_methods,
            allow_http=self.allow_http,
            allow_delete=self.allow_delete,
            rate_limit_per_minute=self.rate_limit_per_minute,
            timeout_seconds=self.timeout_seconds,
            max_request_bytes=self.max_request_bytes,
            max_response_bytes=self.max_response_bytes,
            retries=self.retries,
            follow_redirects=self.follow_redirects,
            credential_scope=self.credential_scope,
            verification_strategy="sha256_receipt",
            rollback_supported=False,
            description=f"Delegated authority generated by {self.issuer}: {self.purpose}",
        )

    def to_private_policy(self) -> PrivateNetworkPolicy:
        if not self.allow_private_network:
            raise AuthorityMintError("private-network authority is not enabled in this profile")
        if not self.private_hosts or not self.private_cidrs:
            raise AuthorityMintError("private-network profile lacks explicit hosts/CIDRs")
        policy = PrivateNetworkPolicy.from_targets(
            self.private_hosts,
            self.private_cidrs,
            allow_http=self.allow_http,
            follow_redirects=self.follow_redirects,
        )
        # PrivateNetworkPolicy itself enforces read-only methods. Keep that invariant even
        # when the public side of the same profile has a wider method set.
        return policy


@dataclass(frozen=True)
class AuthorityMintRequest:
    purpose: str
    allow_hosts: frozenset[str] | None = None
    allowed_methods: frozenset[str] | None = None
    allow_http: bool | None = None
    follow_redirects: bool | None = None
    allow_delete: bool | None = None
    rate_limit_per_minute: int | None = None
    timeout_seconds: float | None = None
    max_request_bytes: int | None = None
    max_response_bytes: int | None = None
    retries: int | None = None
    credential_scope: str | None = None
    allow_private_network: bool | None = None
    private_hosts: frozenset[str] | None = None
    private_cidrs: tuple[str, ...] | None = None
    can_delegate: bool = True


def _fingerprint(data: Mapping[str, Any]) -> str:
    body = dict(data)
    body.pop("fingerprint", None)
    raw = json.dumps(body, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def root_from_external_scope(scope: ExternalAuthorityScope, *, delegation_depth: int = 8) -> AuthorityProfile:
    """Create a trusted root from code-defined ExternalAuthorityScope only."""
    now = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    base = AuthorityProfile(
        profile_id=f"root:{scope.scope_id}",
        issuer="SYSTEM",
        purpose=scope.description or scope.target_service,
        parent_id=None,
        generation=0,
        created_at_utc=now,
        can_delegate=delegation_depth > 0,
        delegation_depth_remaining=max(0, int(delegation_depth)),
        allow_hosts=frozenset(_norm_host(h) for h in scope.allow_hosts),
        allowed_methods=_norm_methods(scope.allowed_methods),
        allow_http=scope.allow_http,
        follow_redirects=scope.follow_redirects,
        allow_delete=scope.allow_delete,
        rate_limit_per_minute=max(1, int(scope.rate_limit_per_minute)),
        timeout_seconds=max(0.5, float(scope.timeout_seconds)),
        max_request_bytes=max(0, int(scope.max_request_bytes)),
        max_response_bytes=max(1024, int(scope.max_response_bytes)),
        retries=max(0, int(scope.retries)),
        credential_scope=scope.credential_scope,
    )
    return dataclasses.replace(base, fingerprint=_fingerprint(base.to_dict()))


def mint_child(parent: AuthorityProfile, request: AuthorityMintRequest, *, issuer: str) -> AuthorityProfile:
    """Mint a recursive child authority while preserving monotonic attenuation."""
    issuer = str(issuer).strip()
    if issuer not in TRUSTED_ISSUERS:
        raise AuthorityMintError(f"issuer is not allowed to mint authority: {issuer}")
    if not parent.can_delegate or parent.delegation_depth_remaining <= 0:
        raise AuthorityMintError("parent authority cannot delegate further")
    if not request.purpose.strip():
        raise AuthorityMintError("child authority requires a purpose")

    hosts = parent.allow_hosts if request.allow_hosts is None else frozenset(_norm_host(x) for x in request.allow_hosts)
    if not hosts.issubset(parent.allow_hosts):
        raise AuthorityMintError("child cannot add hosts outside parent authority")

    methods = parent.allowed_methods if request.allowed_methods is None else _norm_methods(request.allowed_methods)
    if not methods.issubset(parent.allowed_methods):
        raise AuthorityMintError("child cannot add methods outside parent authority")

    allow_http = parent.allow_http if request.allow_http is None else bool(request.allow_http)
    follow_redirects = parent.follow_redirects if request.follow_redirects is None else bool(request.follow_redirects)
    allow_delete = parent.allow_delete if request.allow_delete is None else bool(request.allow_delete)
    if allow_http and not parent.allow_http:
        raise AuthorityMintError("child cannot enable HTTP when parent forbids it")
    if follow_redirects and not parent.follow_redirects:
        raise AuthorityMintError("child cannot enable redirects when parent forbids them")
    if allow_delete and (not parent.allow_delete or "DELETE" not in methods):
        raise AuthorityMintError("child cannot enable DELETE beyond parent/method scope")

    rate = parent.rate_limit_per_minute if request.rate_limit_per_minute is None else int(request.rate_limit_per_minute)
    timeout = parent.timeout_seconds if request.timeout_seconds is None else float(request.timeout_seconds)
    req_bytes = parent.max_request_bytes if request.max_request_bytes is None else int(request.max_request_bytes)
    resp_bytes = parent.max_response_bytes if request.max_response_bytes is None else int(request.max_response_bytes)
    retries = parent.retries if request.retries is None else int(request.retries)
    if not (1 <= rate <= parent.rate_limit_per_minute):
        raise AuthorityMintError("child rate limit must be positive and <= parent")
    if not (0.5 <= timeout <= parent.timeout_seconds):
        raise AuthorityMintError("child timeout must be <= parent")
    if not (0 <= req_bytes <= parent.max_request_bytes):
        raise AuthorityMintError("child request-byte budget must be <= parent")
    if not (1024 <= resp_bytes <= parent.max_response_bytes):
        raise AuthorityMintError("child response-byte budget must be <= parent")
    if not (0 <= retries <= parent.retries):
        raise AuthorityMintError("child retries must be <= parent")

    credential = parent.credential_scope if request.credential_scope is None else str(request.credential_scope)
    if credential not in CREDENTIAL_RANK or parent.credential_scope not in CREDENTIAL_RANK:
        raise AuthorityMintError("unknown credential scope")
    if CREDENTIAL_RANK[credential] > CREDENTIAL_RANK[parent.credential_scope]:
        raise AuthorityMintError("child cannot increase credential authority")

    allow_private = parent.allow_private_network if request.allow_private_network is None else bool(request.allow_private_network)
    if allow_private and not parent.allow_private_network:
        raise AuthorityMintError("child cannot create private-network authority not present in parent")

    private_hosts = parent.private_hosts if request.private_hosts is None else frozenset(_norm_host(x) for x in request.private_hosts)
    if not private_hosts.issubset(parent.private_hosts):
        raise AuthorityMintError("child cannot add private hosts outside parent authority")

    private_cidrs = parent.private_cidrs if request.private_cidrs is None else tuple(str(_network(x)) for x in request.private_cidrs)
    if any(not _cidr_is_within(c, parent.private_cidrs) for c in private_cidrs):
        raise AuthorityMintError("child cannot add/widen private CIDRs outside parent authority")
    if not allow_private:
        private_hosts = frozenset()
        private_cidrs = ()

    next_depth = parent.delegation_depth_remaining - 1
    can_delegate = bool(request.can_delegate and next_depth > 0)
    now = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    profile_id = f"auth:{issuer.lower()}:{uuid.uuid4().hex[:16]}"

    child = AuthorityProfile(
        profile_id=profile_id,
        issuer=issuer,
        purpose=request.purpose.strip(),
        parent_id=parent.profile_id,
        generation=parent.generation + 1,
        created_at_utc=now,
        can_delegate=can_delegate,
        delegation_depth_remaining=next_depth,
        allow_hosts=hosts,
        allowed_methods=methods,
        allow_http=allow_http,
        follow_redirects=follow_redirects,
        allow_delete=allow_delete,
        rate_limit_per_minute=rate,
        timeout_seconds=timeout,
        max_request_bytes=req_bytes,
        max_response_bytes=resp_bytes,
        retries=retries,
        credential_scope=credential,
        allow_private_network=allow_private,
        private_hosts=private_hosts,
        private_cidrs=private_cidrs,
    )
    return dataclasses.replace(child, fingerprint=_fingerprint(child.to_dict()))


class AuthorityRegistry:
    """Persistent registry used by META, X and Senju to mint delegated profiles."""

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        self.profiles: dict[str, AuthorityProfile] = {}

    def seed_builtin_roots(self, *, delegation_depth: int = 8) -> None:
        for scope in BUILTIN_AUTHORITY_SCOPES.values():
            root = root_from_external_scope(scope, delegation_depth=delegation_depth)
            self.profiles.setdefault(root.profile_id, root)

    def get(self, profile_id: str) -> AuthorityProfile:
        try:
            return self.profiles[profile_id]
        except KeyError as exc:
            raise AuthorityMintError(f"unknown parent authority: {profile_id}") from exc

    def mint(self, parent_id: str, request: AuthorityMintRequest, *, issuer: str) -> AuthorityProfile:
        child = mint_child(self.get(parent_id), request, issuer=issuer)
        self.profiles[child.profile_id] = child
        return child

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": REGISTRY_SCHEMA,
            "profiles": [p.to_dict() for p in sorted(self.profiles.values(), key=lambda x: (x.generation, x.profile_id))],
        }

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(self.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> "AuthorityRegistry":
        registry = cls(path)
        p = Path(path)
        if not p.exists():
            return registry
        raw = json.loads(p.read_text(encoding="utf-8"))
        if raw.get("schema") != REGISTRY_SCHEMA:
            raise AuthorityMintError(f"registry schema must be {REGISTRY_SCHEMA}")
        for item in raw.get("profiles") or []:
            profile = AuthorityProfile(
                profile_id=str(item["profile_id"]),
                issuer=str(item["issuer"]),
                purpose=str(item["purpose"]),
                parent_id=item.get("parent_id"),
                generation=int(item["generation"]),
                created_at_utc=str(item["created_at_utc"]),
                can_delegate=bool(item["can_delegate"]),
                delegation_depth_remaining=int(item["delegation_depth_remaining"]),
                allow_hosts=frozenset(item.get("allow_hosts") or []),
                allowed_methods=frozenset(item.get("allowed_methods") or []),
                allow_http=bool(item.get("allow_http", False)),
                follow_redirects=bool(item.get("follow_redirects", False)),
                allow_delete=bool(item.get("allow_delete", False)),
                rate_limit_per_minute=int(item.get("rate_limit_per_minute", 1)),
                timeout_seconds=float(item.get("timeout_seconds", 1.0)),
                max_request_bytes=int(item.get("max_request_bytes", 0)),
                max_response_bytes=int(item.get("max_response_bytes", 1024)),
                retries=int(item.get("retries", 0)),
                credential_scope=str(item.get("credential_scope", "none")),
                allow_private_network=bool(item.get("allow_private_network", False)),
                private_hosts=frozenset(item.get("private_hosts") or []),
                private_cidrs=tuple(item.get("private_cidrs") or []),
                fingerprint=str(item.get("fingerprint") or ""),
                schema=str(item.get("schema") or PROFILE_SCHEMA),
            )
            expected = _fingerprint(profile.to_dict())
            if profile.fingerprint != expected:
                raise AuthorityMintError(f"authority fingerprint mismatch: {profile.profile_id}")
            registry.profiles[profile.profile_id] = profile
        return registry
