#!/usr/bin/env python3
"""
AI FOUNDRY — Autonomous Dev Loop
Uses GitHub Models API (works with GITHUB_TOKEN in Actions).
"""
import json, os, sys, subprocess, urllib.request, urllib.error, time, textwrap
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(os.getenv("REPO_ROOT", ".")).resolve()
TARGETS_FILE = REPO_ROOT / "automation/foundry_agents/improvement_targets.json"
LOOP_STATE_FILE = REPO_ROOT / "automation/foundry_agents/loop_state.json"
REPORT_FILE = Path("/tmp/foundry-dev-report.md")

GH_TOKEN = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN", "")
GH_MODELS_URL = "https://models.inference.ai.azure.com/chat/completions"
MODEL = "gpt-4o-mini"  # fast + cheap, available via GitHub Models
BRANCH = os.getenv("BASE_REF", "audit/reality-gate-v1")
REPO = os.getenv("GITHUB_REPOSITORY", "MusicJapanLLC/the-world2")


def log(msg):
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def load_json(path):
    with open(path) as f:
        return json.load(f)


def save_json(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def pick_target():
    data = load_json(TARGETS_FILE)
    pending = [t for t in data["targets"] if t["status"] == "pending"]
    if not pending:
        return None
    return max(pending, key=lambda t: t["priority"])


def github_models_generate(prompt, system_prompt="You are an expert JavaScript developer."):
    if not GH_TOKEN:
        raise RuntimeError("GITHUB_TOKEN not set")

    payload = json.dumps({
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 3000,
        "temperature": 0.2,
    }).encode()

    req = urllib.request.Request(
        GH_MODELS_URL,
        data=payload,
        headers={
            "Authorization": f"Bearer {GH_TOKEN}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        result = json.load(resp)
    return result["choices"][0]["message"]["content"].strip()


def extract_code(text):
    import re
    m = re.search(r"```(?:javascript|js|typescript|ts)?\n([\s\S]+?)```", text)
    if m:
        return m.group(1).strip()
    if "function " in text or "const " in text or "let " in text:
        return text.strip()
    return None


def build_prompt_for_target(target, current_content):
    app_url = "https://test-musicjapanllc.vercel.app/"
    preview = current_content[:3000] if current_content else "(empty)"
    return textwrap.dedent(f"""
        You are improving AI FOUNDRY IDE ({app_url}).
        Target: [{target['id']}] {target['title']}
        Description: {target['description']}

        The file to modify is: {target['files'][0]}
        Current file content (first 3000 chars):
        ```
        {preview}
        ```

        Generate ONLY a JavaScript code block that implements this improvement.
        The code will be APPENDED to the end of the file.
        Output a single self-contained function or IIFE.
        No explanation, no markdown outside the code fence, just:
        ```javascript
        // your code here
        ```
    """).strip()


def get_file_content(file_path):
    full = REPO_ROOT / file_path
    if full.exists():
        return full.read_text(encoding="utf-8")
    return ""


def apply_improvement(target, code):
    file_path = REPO_ROOT / target["files"][0]
    current = file_path.read_text(encoding="utf-8")
    comment = "#" if file_path.suffix == ".py" else "//"
    marker = f"{comment} ── FORGE: {target['id']} ──"
    if marker in current:
        log(f"  Marker already present in {target['files'][0]}, skipping append")
        return False
    new_content = current + f"\n\n{marker}\n{code}\n"
    file_path.write_text(new_content, encoding="utf-8")
    return True


def smoke_test():
    for js_file in (REPO_ROOT / "public").glob("*.js"):
        r = subprocess.run(["node", "--check", str(js_file)], capture_output=True)
        if r.returncode != 0:
            raise RuntimeError(f"Syntax error in {js_file.name}: {r.stderr.decode()[:300]}")
    for js_file in (REPO_ROOT / "api").glob("*.js"):
        r = subprocess.run(["node", "--check", str(js_file)], capture_output=True)
        if r.returncode != 0:
            raise RuntimeError(f"Syntax error in {js_file.name}: {r.stderr.decode()[:300]}")
    log("  Smoke test passed")


def git_commit_push(target, code_preview):
    subprocess.run(["git", "config", "user.email", "forge@ai-foundry"], cwd=REPO_ROOT, check=True)
    subprocess.run(["git", "config", "user.name", "AI FOUNDRY Bot"], cwd=REPO_ROOT, check=True)

    subprocess.run(["git", "add", "-A"], cwd=REPO_ROOT, check=True)

    msg = (
        f"feat(forge): {target['id']} — {target['title']}\n\n"
        f"Generated by AI FOUNDRY autonomous dev loop\n"
        f"Model: {MODEL}\nTarget: {target['id']}\n"
        f"Preview: {code_preview[:120]}\n\n"
        f"Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
    )
    subprocess.run(["git", "commit", "-m", msg], cwd=REPO_ROOT, check=True)

    for attempt, delay in enumerate([2, 4, 8, 16], 1):
        r = subprocess.run(
            ["git", "push", "-u", "origin", BRANCH],
            cwd=REPO_ROOT, capture_output=True
        )
        if r.returncode == 0:
            log(f"  Pushed on attempt {attempt}")
            return True
        log(f"  Push failed (attempt {attempt}): {r.stderr.decode()[:200]}")
        if attempt < 4:
            time.sleep(delay)

    raise RuntimeError("git push failed after 4 attempts")


def update_target_status(target_id, status):
    data = load_json(TARGETS_FILE)
    for t in data["targets"]:
        if t["id"] == target_id:
            t["status"] = status
            t["implemented_at"] = datetime.now(timezone.utc).isoformat()
    save_json(TARGETS_FILE, data)


def update_loop_state(target_id):
    state = {}
    if LOOP_STATE_FILE.exists():
        state = load_json(LOOP_STATE_FILE)
    state["cycle_count"] = state.get("cycle_count", 0) + 1
    state["last_target"] = target_id
    state["last_run"] = datetime.now(timezone.utc).isoformat()
    save_json(LOOP_STATE_FILE, state)


def append_report(target, success, note=""):
    ts = datetime.now(timezone.utc).isoformat()
    line = f"| {ts} | {target['id']} | {target['title']} | {'✅' if success else '❌'} | {note} |\n"
    if not REPORT_FILE.exists():
        REPORT_FILE.write_text("# AI FOUNDRY Dev Report\n\n| Time | ID | Title | Status | Note |\n|------|-----|-------|--------|------|\n")
    with REPORT_FILE.open("a") as f:
        f.write(line)


def main():
    log("=== AI FOUNDRY Autonomous Dev Loop ===")

    if not GH_TOKEN:
        log("ERROR: GITHUB_TOKEN not set — cannot call GitHub Models API")
        sys.exit(1)

    target = pick_target()
    if not target:
        log("No pending targets — all done!")
        sys.exit(0)

    log(f"Target: [{target['id']}] {target['title']} (priority={target['priority']})")

    try:
        current = get_file_content(target["files"][0])
        prompt = build_prompt_for_target(target, current)

        log(f"  Calling GitHub Models API ({MODEL})…")
        response = github_models_generate(prompt)
        code = extract_code(response)

        if not code:
            raise RuntimeError("GitHub Models returned no usable code")

        log(f"  Generated {len(code)} chars of code")

        applied = apply_improvement(target, code)
        if not applied:
            log("  Already implemented, skipping")
            sys.exit(0)

        smoke_test()
        update_target_status(target["id"], "implemented")
        update_loop_state(target["id"])

        git_commit_push(target, code)
        append_report(target, True, "via GitHub Models API")
        log(f"✅ Done: {target['id']} shipped to {BRANCH}")

    except Exception as e:
        log(f"❌ Error: {e}")
        # Roll back file changes on failure
        subprocess.run(["git", "checkout", "--", "."], cwd=REPO_ROOT)
        append_report(target, False, str(e)[:120])
        sys.exit(1)


if __name__ == "__main__":
    main()
