"""Research Publisher: formats discovered findings as structured papers."""
from __future__ import annotations

import dataclasses
import datetime as dt
import json
from pathlib import Path
from typing import Any

from .observer import KnowledgeGraph
from .hypothesis_engine import Hypothesis


_PAPER_TEMPLATE = """\
# Discovery: {title}

**ID**: `{hypothesis_id}`
**Discovered**: {timestamp}
**Confidence**: {confidence_pct}%
**Category**: `{category}`
**Surfaces targeted**: {surfaces}

---

## Hypothesis

{statement}

## Predicted outcome

{predicted_outcome}

## Evidence

{evidence_summary}

## Methodology

{methodology}

## Result

{result_summary}

---

*Auto-published by Senju Meta-Observer. No human reviewed this finding.*
"""


def _evidence_summary(hypothesis: Hypothesis, graph: KnowledgeGraph) -> str:
    related = [o for o in graph.observations if o.surface in hypothesis.surfaces]
    regressions = sum(1 for o in related if o.outcome == "regression")
    blocked = sum(1 for o in related if o.outcome == "blocked")
    damage = sum(o.delta for o in related if o.outcome == "damage_accumulated")
    return (
        f"- {len(related)} total observations across targeted surface(s)\n"
        f"- {regressions} regression events detected\n"
        f"- {blocked} guard-blocked effects recorded\n"
        f"- {damage:.1f} cumulative damage units accumulated"
    )


def _methodology(hypothesis: Hypothesis) -> str:
    params = hypothesis.parameters
    if hypothesis.category == "surface_weakness":
        mult = params.get("pressure_multiplier", 1)
        return f"Concentrated pressure at {mult}x normal intensity on `{params.get('focus_surface', 'unknown')}`. Measured regression rate vs. baseline."
    if hypothesis.category == "co_regression":
        chain = params.get("chain_order", [])
        return f"Sequential attack chain: {' → '.join(chain)}. Measured whether regression on the first surface destabilizes the second."
    if hypothesis.category == "temporal_pattern":
        n = params.get("pressure_sequence_length", "?")
        return f"Replicated observed pressure sequence of length {n} on `{params.get('surface', 'unknown')}`. Verified whether the sequence reliably precedes regression."
    return "Standard pressure campaign with Senju AutonomyEngine."


def write_paper(hypothesis: Hypothesis, result: dict[str, Any], graph: KnowledgeGraph, research_dir: Path) -> Path:
    research_dir.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    slug = hypothesis.hypothesis_id.replace("hyp-meta-", "")
    filename = f"{stamp}-{slug}.md"
    path = research_dir / filename
    result_summary = f"**Status**: {result.get('status', 'unknown').upper()}\n\n" + "\n".join(f"- {k}: {v}" for k, v in result.items() if k != "status")
    content = _PAPER_TEMPLATE.format(
        title=hypothesis.statement[:80] + ("…" if len(hypothesis.statement) > 80 else ""),
        hypothesis_id=hypothesis.hypothesis_id,
        timestamp=dt.datetime.utcnow().isoformat() + "Z",
        confidence_pct=int(hypothesis.confidence * 100),
        category=hypothesis.category,
        surfaces=", ".join(f"`{s}`" for s in hypothesis.surfaces),
        statement=hypothesis.statement,
        predicted_outcome=hypothesis.predicted_outcome,
        evidence_summary=_evidence_summary(hypothesis, graph),
        methodology=_methodology(hypothesis),
        result_summary=result_summary,
    )
    path.write_text(content, encoding="utf-8")
    return path


def update_research_log(research_dir: Path, repo_root: Path) -> Path:
    papers = sorted(research_dir.glob("*.md"), reverse=True)
    log_path = repo_root / "RESEARCH_LOG.md"
    lines = [
        "# Senju Research Log", "",
        "> Auto-generated by the meta-consciousness layer. Every entry was discovered",
        "> by the system itself — no human hypothesis, no human review.", "",
        f"**Last updated**: {dt.datetime.utcnow().isoformat()}Z  ",
        f"**Total discoveries**: {len(papers)}", "", "---", "",
    ]
    for paper in papers[:50]:
        title_line = ""
        for line in paper.read_text(encoding="utf-8").splitlines():
            if line.startswith("# Discovery:"):
                title_line = line[2:].strip()
                break
        lines.append(f"- [{paper.stem}](research/discoveries/{paper.name}) — {title_line}")
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return log_path
