// GitHub integration: repo read + PR creation
function body(req) {
  if (req.body && typeof req.body === 'object') return req.body;
  if (typeof req.body === 'string') { try { return JSON.parse(req.body); } catch { return {}; } }
  return {};
}

function send(res, status, data) {
  res.status(status).setHeader('Content-Type', 'application/json; charset=utf-8');
  res.end(JSON.stringify(data));
}

function parseRepoUrl(url) {
  const m = String(url || '').match(/github\.com[/:](\w[\w.-]+)\/(\w[\w.-]+?)(?:\.git)?(?:\/|$)/);
  if (!m) throw new Error('GitHub URL が認識できません (github.com/owner/repo 形式で入力してください)');
  return { owner: m[1], repo: m[2] };
}

async function ghFetch(path, token, opts = {}) {
  const headers = { Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'AI-FOUNDRY-IDE/1' };
  if (token) headers.Authorization = `Bearer ${token}`;
  const res = await fetch(`https://api.github.com${path}`, { ...opts, headers: { ...headers, ...opts.headers } });
  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    throw new Error(`GitHub API ${res.status}: ${txt.slice(0, 200)}`);
  }
  return res.json();
}

function decodeContent(b64) {
  return decodeURIComponent(escape(atob(b64.replace(/\s/g, ''))));
}

async function readRepo(payload) {
  const { owner, repo } = parseRepoUrl(payload.url);
  const token = payload.token || null;

  const [readmeData, treeData] = await Promise.allSettled([
    ghFetch(`/repos/${owner}/${repo}/readme`, token),
    ghFetch(`/repos/${owner}/${repo}/git/trees/HEAD?recursive=1`, token),
  ]);

  let readme = '';
  if (readmeData.status === 'fulfilled') {
    try { readme = decodeContent(readmeData.value.content || ''); } catch { readme = ''; }
    readme = readme.slice(0, 8000);
  }

  let files = [];
  if (treeData.status === 'fulfilled') {
    files = (treeData.value.tree || [])
      .filter(f => f.type === 'blob')
      .map(f => f.path)
      .slice(0, 200);
  }

  const srcFiles = files.filter(p => /\.(js|ts|tsx|jsx|py|go|rs)$/.test(p) && !p.includes('node_modules')).slice(0, 3);
  const srcContents = await Promise.allSettled(
    srcFiles.map(p => ghFetch(`/repos/${owner}/${repo}/contents/${encodeURIComponent(p)}`, token))
  );

  let srcBlocks = '';
  srcContents.forEach((r, i) => {
    if (r.status === 'fulfilled') {
      try {
        const text = decodeContent(r.value.content || '').slice(0, 4000);
        srcBlocks += `\n\n### ${srcFiles[i]}\n\`\`\`\n${text}\n\`\`\``;
      } catch { /* skip */ }
    }
  });

  const context = `# ${owner}/${repo}\n\n## README\n${readme || '(No README)'}\n\n## File tree (first 200)\n${files.join('\n')}${srcBlocks}`;
  return { owner, repo, context: context.slice(0, 20000), fileCount: files.length };
}

async function createPr(payload) {
  const { owner, repo } = parseRepoUrl(payload.url);
  const token = payload.token;
  if (!token) throw new Error('GitHub PAT (token) が必要です');

  const { title, body: prBody, head, base = 'main', files = [] } = payload;
  if (!title || !head) throw new Error('title と head ブランチ名が必要です');

  if (files.length > 0) {
    const repoInfo = await ghFetch(`/repos/${owner}/${repo}`, token);
    const defaultBranch = base || repoInfo.default_branch || 'main';
    const refData = await ghFetch(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`, token);
    const baseSha = refData.object.sha;

    await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
      body: JSON.stringify({ ref: `refs/heads/${head}`, sha: baseSha }),
    });

    for (const f of files) {
      const content = btoa(unescape(encodeURIComponent(f.content || '')));
      await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(f.path)}`, {
        method: 'PUT',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
        body: JSON.stringify({ message: f.message || `AI FOUNDRY: update ${f.path}`, content, branch: head }),
      });
    }
  }

  const pr = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ title, body: prBody || 'Generated by AI FOUNDRY IDE', head, base }),
  });
  if (!pr.ok) {
    const err = await pr.text().catch(() => '');
    throw new Error(`PR作成失敗 (${pr.status}): ${err.slice(0, 200)}`);
  }
  const prData = await pr.json();
  return { url: prData.html_url, number: prData.number, title: prData.title };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return send(res, 405, { error: 'POST required' });
  const payload = body(req);
  const action = typeof payload.action === 'string' ? payload.action : '';
  try {
    if (action === 'read_repo') return send(res, 200, await readRepo(payload));
    if (action === 'create_pr') return send(res, 200, await createPr(payload));
    return send(res, 400, { error: 'unknown action: use read_repo or create_pr' });
  } catch (err) {
    console.error('GitHub API handler error', err);
    return send(res, 500, { error: err instanceof Error ? err.message : 'request failed' });
  }
}
